# Generated by Django 4.2 on 2024-10-24 08:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("investment", "Investment"),
                            ("virtual_tax", "Virtual Tax"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("internal", "Internal"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tax_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "destination_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_to",
                        to="tracker.account",
                    ),
                ),
                (
                    "origin_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_from",
                        to="tracker.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("year", models.IntegerField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_account",
                        to="tracker.account",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_transaction",
                        to="tracker.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("salary", "Salary"),
                            ("interest", "Interest"),
                            ("parents", "Parents"),
                            ("birthday", "Birthday"),
                            ("iva_reimbursement", "IVA_Reimbursement"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_account",
                        to="tracker.account",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_transaction",
                        to="tracker.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("accessories", "Accessories"),
                            ("books", "Books"),
                            ("car", "Car"),
                            ("cash", "Cash"),
                            ("clothing", "Clothing"),
                            ("coffees & snacks", "Coffees & Snacks"),
                            ("dining out", "Dining Out"),
                            ("entertainment", "Entertainment"),
                            ("fees", "Fees"),
                            ("gifts", "Gifts"),
                            ("groceries", "Groceries"),
                            ("gym", "Gym"),
                            ("haircut", "Haircut"),
                            ("housing", "Housing"),
                            ("insurance", "Insurance"),
                            ("healthcare", "Healthcare"),
                            ("miscellaneous", "Miscellaneous"),
                            ("office", "Office"),
                            ("personal development", "Personal Development"),
                            ("petrol", "Petrol"),
                            ("pharmacy", "Pharmacy"),
                            ("phone", "Phone"),
                            ("rent", "Rent"),
                            ("sports", "Sports"),
                            ("supplements", "Supplements"),
                            ("tattoo", "Tattoo"),
                            ("taxes", "Taxes"),
                            ("tech", "Tech"),
                            ("transportation", "Transportation"),
                            ("utilities", "Utilities"),
                            ("vacation", "Vacation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "source",
                    models.CharField(
                        choices=[("personal", "Personal"), ("shared", "Shared")],
                        max_length=50,
                    ),
                ),
                (
                    "fixed_or_variable",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("variable", "Variable")],
                        max_length=50,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_account",
                        to="tracker.account",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_transaction",
                        to="tracker.transaction",
                    ),
                ),
            ],
        ),
    ]
