# Generated by Django 4.2 on 2024-10-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_alter_transaction_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
