# Generated by Django 4.2 on 2024-11-06 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0006_alter_transaction_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="transaction_type",
            new_name="type",
        ),
    ]
