# Generated by Django 4.2 on 2024-11-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0008_remove_transaction_fee_alter_expense_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="tax_percentage",
        ),
        migrations.AlterField(
            model_name="income",
            name="category",
            field=models.CharField(
                choices=[
                    ("salary", "Salary"),
                    ("interest", "Interest"),
                    ("parents", "Parents"),
                    ("birthday", "Birthday"),
                    ("iva_reimbursement", "IVA Reimbursement"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("income", "Income"),
                    ("expense", "Expense"),
                    ("internal", "Internal"),
                    ("tax", "Tax"),
                ],
                max_length=10,
            ),
        ),
    ]
