# Generated by Django 4.2 on 2024-11-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0009_remove_transaction_tax_percentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("accessories", "Accessories"),
                    ("books", "Books"),
                    ("car", "Car"),
                    ("cash", "Cash"),
                    ("clothing", "Clothing"),
                    ("coffees & snacks", "Coffees & Snacks"),
                    ("dining out", "Dining Out"),
                    ("entertainment", "Entertainment"),
                    ("fees", "Fees"),
                    ("gifts", "Gifts"),
                    ("groceries", "Groceries"),
                    ("gym", "Gym"),
                    ("haircut", "Haircut"),
                    ("housing", "Housing"),
                    ("insurance", "Insurance"),
                    ("healthcare", "Healthcare"),
                    ("miscellaneous", "Miscellaneous"),
                    ("office", "Office"),
                    ("personal development", "Personal Development"),
                    ("petrol", "Petrol"),
                    ("pharmacy", "Pharmacy"),
                    ("phone", "Phone"),
                    ("rent", "Rent"),
                    ("sports", "Sports"),
                    ("supplements", "Supplements"),
                    ("tattoo", "Tattoo"),
                    ("taxes", "Taxes"),
                    ("tech", "Tech"),
                    ("transportation", "Transportation"),
                    ("utilities", "Utilities"),
                    ("vacation", "Vacation"),
                ],
                max_length=50,
            ),
        ),
    ]
