# Generated by Django 4.2 on 2025-01-02 19:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0010_alter_expense_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountBalanceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_history",
                        to="tracker.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "unique_together": {("account", "timestamp")},
            },
        ),
    ]
