# Generated by Django 4.2 on 2025-01-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0012_account_user_alter_transaction_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("accessories", "Accessories"),
                    ("books", "Books"),
                    ("car", "Car"),
                    ("cash", "Cash"),
                    ("clothing", "Clothing"),
                    ("coffees & snacks", "Coffees & Snacks"),
                    ("dining out", "Dining Out"),
                    ("entertainment", "Entertainment"),
                    ("farm", "Farm"),
                    ("fees", "Fees"),
                    ("gifts", "Gifts"),
                    ("groceries", "Groceries"),
                    ("gym", "Gym"),
                    ("housing", "Housing"),
                    ("insurance", "Insurance"),
                    ("medical appointments", "Medical Appointments"),
                    ("miscellaneous", "Miscellaneous"),
                    ("personal care", "Personal Care"),
                    ("personal development", "Personal Development"),
                    ("pet", "Pet"),
                    ("petrol", "Petrol"),
                    ("pharmacy", "Pharmacy"),
                    ("phone", "Phone"),
                    ("renovation", "Renovation"),
                    ("sports", "Sports"),
                    ("supplements", "Supplements"),
                    ("tattoos", "Tattoos"),
                    ("taxes", "Taxes"),
                    ("transportation", "Transportation"),
                    ("utilities", "Utilities"),
                    ("vacation", "Vacation"),
                    ("workspace", "Workspace"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="category",
            field=models.CharField(
                choices=[
                    ("salary", "Salary"),
                    ("interest", "Interest"),
                    ("parents", "Parents"),
                    ("joint transfer", "Joint Transfer"),
                    ("birthday", "Birthday"),
                    ("christmas", "Christmas"),
                    ("tax", "Tax"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
