# Generated by Django 4.2 on 2025-01-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0013_alter_expense_category_alter_income_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("accessories", "Accessories"),
                    ("car", "Car"),
                    ("cash", "Cash"),
                    ("clothing", "Clothing"),
                    ("coffees & snacks", "Coffees & Snacks"),
                    ("dining out", "Dining Out"),
                    ("entertainment", "Entertainment"),
                    ("farm", "Farm"),
                    ("fees", "Fees"),
                    ("gifts", "Gifts"),
                    ("groceries", "Groceries"),
                    ("gym", "Gym"),
                    ("housing", "Housing"),
                    ("medical appointments", "Medical Appointments"),
                    ("miscellaneous", "Miscellaneous"),
                    ("personal care", "Personal Care"),
                    ("personal development", "Personal Development"),
                    ("pet", "Pet"),
                    ("petrol", "Petrol"),
                    ("pharmacy", "Pharmacy"),
                    ("phone", "Phone"),
                    ("sports", "Sports"),
                    ("supplements", "Supplements"),
                    ("tattoos", "Tattoos"),
                    ("taxes", "Taxes"),
                    ("transportation", "Transportation"),
                    ("utilities", "Utilities"),
                    ("vacation", "Vacation"),
                    ("wedding", "Wedding"),
                    ("workspace", "Workspace"),
                ],
                max_length=50,
            ),
        ),
    ]
